name: server_custom_middleware
description: An example to demonstrate the use of custom server middleware in a jaspr app.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  jaspr_builder: ^0.10.0
  lints: ^3.0.0

jaspr:
  uses-ssr: true
