name: package_riverpod
description: An example showing how to use riverpod with jaspr.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.10.0
  jaspr_riverpod: ^0.3.9

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  jaspr_builder: ^0.10.0
  lints: ^3.0.0

jaspr:
  uses-ssr: true
