name: flutter_plugin_interop
description: A pure client-side app without ssr.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.10.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.8
  jaspr_builder: ^0.10.0
  jaspr_web_compilers: ^4.0.7
  lints: ^3.0.0

jaspr:
  uses-ssr: true
