name: flutter_embedding_demo
description: A demo of embedding a flutter app into a jaspr website.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: 1.0.6
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  jaspr: ^0.10.0
  jaspr_flutter_embed: ^0.2.0
  jaspr_riverpod: ^0.3.9
  js: ^0.7.1
  riverpod: ^2.4.8

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  jaspr_builder: ^0.10.0
  jaspr_web_compilers: ^4.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/dash.png

jaspr:
  uses-ssr: true
  uses-flutter: true
